// <auto-generated />
using GroceryStoreManagement.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroceryStoreManagement.Migrations
{
    [DbContext(typeof(GroceryDbContext))]
    [Migration("20220915052712_Initialmigration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GroceryStoreManagement.Models.CartModel", b =>
                {
                    b.Property<int>("GroceryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroceryName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("GroceryPrice")
                        .HasColumnType("int");

                    b.Property<int>("GroceryRating")
                        .HasColumnType("int");

                    b.Property<string>("GroceryType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroceryId");

                    b.ToTable("CartModel");
                });

            modelBuilder.Entity("GroceryStoreManagement.Models.GroceryModel", b =>
                {
                    b.Property<int>("GroceryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroceryName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("GroceryPrice")
                        .HasColumnType("int");

                    b.Property<int>("GroceryRating")
                        .HasColumnType("int");

                    b.Property<string>("GroceryType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroceryId");

                    b.ToTable("GroceryModel");
                });

            modelBuilder.Entity("GroceryStoreManagement.Models.OrderModel", b =>
                {
                    b.Property<int>("GroceryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroceryName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("GroceryPrice")
                        .HasColumnType("int");

                    b.Property<int>("GroceryRating")
                        .HasColumnType("int");

                    b.Property<string>("GroceryType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroceryId");

                    b.ToTable("OrderModel");
                });

            modelBuilder.Entity("GroceryStoreManagement.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserModel");
                });
#pragma warning restore 612, 618
        }
    }
}
